[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vibe-cli"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["requests", "typer"]

[project.scripts]
vibe = "cli.vibe:main"

[tool.setuptools]
packages = ["cli"]
